### ISSUE TITLE
Clean up the page(s) related to reviewing content

### ISSUE THREAD

**Issue by phae** [chimecms/chime#116]
I think it's just a box someone types into at the moment, and needs some shining to make it clearer what's going on.

**Comment by norrishung** [comment]
This is potentially a bigger umbrella task that needs to be broken up. Sub-tasks that need to happen in order to complete this include:

1. Figure out how to deal with the issue when multiple people are trying to review the same activity (lock activity so only one person can be reviewing it?)

2. Create an activity-review page that shows the reviewer a list of modified files.

3. Create an article-review page that gives the reviewer a view-only mode of the article and allows the reviewer to provide activity-level feedback.

4. Update activities-list page so that there is a clearer division between different stages of activities:
    - new activity (no changes)
    - new activity (changes made and can be submitted for review)
    - activity that has been submitted for review
    - activity that has been reviewed and needs fixes

5. Ability to filter between your tasks and someone else's activities in the activities-list view.

6. Upon hitting the "review activity" button, user should be taken to the activity-review page, not the articles-list page.

7. UI for the activity author to review feedback.

8. Make it impossible for anyone but the activity author to submit the activity for review.

9. Decide whether anyone besides the activity author should be able to make changes in an activity. (yes?)

**Comment by phae** [comment]
OK, here's a checklist:

* [ ] #144 - list 'files edited for this task' at top of file explorer
* [ ] #229 - Actually set review flags when a reviewer has been requested
* [ ] #248 Create an Activity dashboard layout
* [ ] #249 Remove peer rejected flag
* [ ] #250 Add "changes submitted" state to an activity
* [ ] #251 Add activity bar to all pages within an activity
