### ISSUE TITLE
Catch errors when task is published or deleted and someone continues working

### ISSUE THREAD

**Issue by norrishung** [chimecms/chime#349]
Umbrella task for:

- [ ] #348: Users should not be able to recreate a dead branch
- [ ] #347: Display flash error when origin activity doesn't exist.
- [ ] #346: Add sync decorator to actions within an activity
- [x] #287: python daemon syncs for backup
